[package]
name = "radio-streamer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
axum = { version = "0.8", features = ["macros"] }
tower-http = { version = "0.6", features = ["cors", "fs"] }
bytes = "1.10"
futures-util = "0.3"
async-stream = "0.3"
id3 = "1.16"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
walkdir = "2.5"
symphonia = { version = "0.5", features = ["mp3", "pcm", "isomp4"] }
memmap2 = "0.9"
mp3lame-sys = "0.1"
